services:
  - type: web
    name: ph-portfolio
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run preview
    envVars:
      - key: GEMINI_API_KEY
        scope: build
